server:
  port: 80

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/  #集群版
  instance:
    instance-id: consumer-order80
    prefer-ip-address: true
    #eureka客户端向服务端发送心跳的时间间隔（默认30秒）
#    lease-renewal-interval-in-seconds: 1
    #eureka服务端在收到最后一次心跳等待时间上限（90秒），超时提出
#    lease-expiration-duration-in-seconds: 2
spring:
  application:
    name: cloud-order-comsuer-service