#consul服务端口号
server:
  port: 8006



spring:
  application:
    name: cloud-providerconsul-payment8006

####consul注册中心
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}

