server:
  port: 8001


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: payment-hystrix8001
    prefer-ip-address: true
spring:
  application:
    name: payment-eureka-hystrix
#    eviction-interval-timer-in-ms: 2000
